oebs:
  environment: OEBSQ2
  version: 1.0.0
  date: 21.08.2026

spring:
  datasource:
    url: ${ORACLE_URL}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none